apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.tableName | dump }}
  annotations:
    github.com/project-slug: ${{ values.githubOrg | trim }}/${{ values.githubRepo | trim }}
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
